version: '2'

services:
    rancher-ssl:
        image: rancher/server:preview
        restart: always
        ports:
          - "80:80/tcp"
          - "443:443/tcp"
        volumes:
            - /usr/local/etc/rancher/mysql:/var/lib/mysql