version: '2'

services:
    rancher:
        image: rancher/server
        container_name: rancher-server
        restart: always
    nginx:
        image: nginx:1.11
        volumes:
            - /usr/local/etc/nginx/rancher.conf:/etc/nginx/conf.d/rancher.conf
            - /usr/local/etc/nginx/ssl:/usr/local/etc/nginx/ssl
        ports:
            - "81:80/tcp"
            - "443:443/tcp"
        restart: always