version: '2'

services:
    rancher-ssl:
        image: rancher/server:stable
        restart: always
    nginx:
        build: .
        volumes:
            - /usr/local/etc/nginx/ssl:/usr/local/etc/nginx/ssl
        ports:
            - "443:443/tcp"
        restart: always